micronaut:
  application:
    name: mongomicronaut
netty:
  default:
    allocator:
      max-order: 3
#mongodb.uri: mongodb://${MONGO_HOST:mongo1}:${MONGO_PORT:27017}
mongodb:
  uri: mongodb://mongoreplica1:27017,mongoreplica2:27017,mongoreplica3:27017
db:
  name: 'fruit'
  collection: 'fruit'