micronaut:
  application:
    name: mongomicronaut
netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://${MONGO_HOST:mongo1}:${MONGO_PORT:27017}/mydb
db:
  name: 'fruit'
  collection: 'fruit'