name: Compile, Package Native App & Publish Docker Image

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  release:
    types: [ published ]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Compile and test with Maven
        run: mvn -B test --file pom.xml

      - name: Setup GraalVM environment
        if: success()
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.0.0.2.java11'

      - name: Install GraalVM's native-image extension
        if: success()
        run: gu install native-image    
        
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      - name: Build a docker image
        if: success()
        run: ./mvnw package -Dpackaging=docker-native -Pgraalvm

      - name: Push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
